# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backtest', '0002_backtest_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='error_info',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
