# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backtest', '0003_backtest_error_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PROCESSING', 'PROCESSING'), ('ERROR', 'ERROR')], default='PROCESSING', max_length=50),
        ),
    ]
